require("dotenv").config()
const PORT= process.env.PORT;
const {app} = require("./app")
const {dbConect} = require("./db/db")

dbConect();

app.listen(PORT,()=>{
    console.log("corriendo servidor")

})

//TODO: REGISTER AND LOGIN 
//TODO: CREATE A POST AND UPLOAD IMG 
//TODO: GENERATE TOKEN COOKIES 
//TODO: GET THE AUTHOR NAME FROM THE TOKEN AND ID DECODED USING A MIDDLEWARE
//TODO: DELETE A POST BY ID
//TODO: READ THE BLOGS AND ONE BY ID 
//TODO: LOGOUT COOKIE SESSION
//TODO: LIKES, UNLIKES AND COMMENTS BY USER => DONE
//TODO:  UPDATE PROFILE && POSTS BY ID 
// DONE: MEJORAR SEGURIDAD DE AUTH Y OTRA MANERA DE ALMACENAR ARCHIVOS(IMAGENES) USING CLOUDINARY
//VALIDATE DATA FROM CLIENT DONE 